[dependencies.wasm-project]
default-features = false
features = []
package = 'node-template-runtime'
path = '/Users/mac/work-files/coding/git-files/paritytech-learning/advanced-learning/03_polkadot-js-api/kitties/node/runtime'

[lib]
crate-type = ['cdylib']
name = 'node_template_runtime'

[package]
edition = '2018'
name = 'node-template-runtime-wasm'
resolver = '2'
version = '1.0.0'
[profile.dev]
panic = 'abort'

[profile.release]
lto = true
panic = 'abort'

[workspace]
